[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd backend && node src/app.js"
