[phases.setup]
nixPkgs = ["nodejs-18_x"]
nixpacksVersion = "1.38.0"

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && npm install --production"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node backend/src/app.js"
