[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node backend/scripts/replaceAmazonProductsInProduction.js && node backend/src/app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
