[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm run start:production"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
