[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --production"

[deploy]
startCommand = "cd backend && node src/app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
